[package]
name = "otmp-core-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OpenTTD game launcher core"

[dependencies]
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"